---
- name: check docker exitence
  hosts: all
  #become: true
  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_check
      ignore_errors: true

    - name: Display Docker status
      ansible.builtin.debug:
        msg: "{{ 'Docker is installed: ' + docker_check.stdout if docker_check.rc == 0 else 'Docker is not installed' }}"
