services:
  web:
    image: nginx:alpine
    container_name: test
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - testnet

networks:
  testnet:
    driver: bridge